# Generated by Django 5.1.1 on 2024-09-21 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='選單名稱')),
                ('icon', models.CharField(max_length=100, null=True, verbose_name='選單圖示')),
                ('parent_id', models.IntegerField(null=True, verbose_name='父選單ID')),
                ('order_num', models.IntegerField(null=True, verbose_name='顯示順序')),
                ('path', models.CharField(max_length=200, null=True, verbose_name='路由地址')),
                ('component', models.CharField(max_length=255, null=True, verbose_name='組件路徑')),
                ('menu_type', models.CharField(max_length=1, null=True, verbose_name='選單類型 - M目錄 C選單 F按鈕')),
                ('perms', models.CharField(max_length=100, null=True, verbose_name='權限標識')),
                ('create_time', models.DateField(null=True, verbose_name='創建時間')),
                ('update_time', models.DateField(null=True, verbose_name='更新時間')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='備註')),
            ],
            options={
                'db_table': 'sys_menu',
            },
        ),
        migrations.CreateModel(
            name='SysRoleMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.sysmenu')),
            ],
            options={
                'db_table': 'sys_role_menu',
            },
        ),
    ]
